# Generated by Django 5.0.3 on 2024-05-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=100, verbose_name='Номер заказа')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Заказчик')),
                ('product_name', models.CharField(max_length=100, verbose_name='Продукт')),
                ('order_date', models.DateTimeField(verbose_name='Дата публикации')),
                ('status', models.CharField(max_length=50, verbose_name='Статус')),
            ],
        ),
    ]
